#!/usr/bin/env bash
# Credit: https://stackoverflow.com/questions/28320134/how-to-list-all-tags-for-a-docker-image-on-a-remote-registry

set -e

IMAGE="$1"

if [[ -z "$IMAGE" ]]; then
	echo "Error: Please provide a docker image name"
	echo "Usage: docker-list-tags <image name>"
	echo "Example: docker-list-tags mysql"
	exit 1
fi

RESPONSE=$(curl -L -s "https://registry.hub.docker.com/v1/repositories/$IMAGE/tags")

if [[ "$RESPONSE" == *"Resource not found"* ]]; then
	echo "The image '$IMAGE' does not exist in the official Docker registry (Resource not found)"
	exit 1
fi

VERSIONS=$(echo "$RESPONSE" | jq -r '.[].name')

echo "Available tags for '$IMAGE':"
echo
column <(echo "$VERSIONS")
